# Generated by Django 2.2.5 on 2019-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fbcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='anonymous')),
                ('feedback', models.TextField(default='no feedback')),
                ('stdid', models.IntegerField(default=0)),
                ('email', models.TextField(default='noemail')),
                ('pillar', models.TextField(default='nopillar')),
                ('category', models.TextField(default='nocat')),
            ],
        ),
    ]
