# Generated by Django 2.2.4 on 2019-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fbcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.TextField()),
                ('feedback', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
    ]
