# Generated by Django 2.2.4 on 2019-08-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbcontent',
            name='date',
        ),
    ]
